INSERT INTO publisher (publisher, discount) VALUES 
('Chatto & Windus', 8.83),
('Covici Friede', 8.86),
('Harper & Brothers', 1.77),
('Charles Scribners Sons', 5.65),
('Hogarth Press', 7.43),
('The Russian Messenger', 5.35),
('T. Egerton, Whitehall', 1.36),
('Ballantine Books', 4.92),
('Allen & Unwin', 0.99),
('J. B. Lippincott & Co.', 8.71),
('McClelland and Stewart', 2.12),
('Chapman & Hall', 10.27),
('Bloomsbury Publishing', 4.40),
('Editorial Sudamericana', 1.09),
('Gallimard', 7.13),
('Alfred A. Knopf', 8.26),
('Pierre-Jules Hetzel', 9.90),
('Secker and Warburg', 8.76),
('Delacorte Press', 7.72);
